[tool.towncrier]
package = "exceptiongroup"
filename = "docs/source/history.rst"
directory = "newsfragments"
underlines = ["-", "~", "^"]
issue_format = "`#{issue} <https://github.com/python-trio/exceptiongroup/issues/{issue}>`__"

[tool.black]
line-length = 79
